Update verifyCntlrsFlash to check for rsh availability
The Python script relies on rsh and does not run properly if it is unavailable.

diff --git a/src/ddr/adm/acq/verifyCntlrsFlash b/src/ddr/adm/acq/verifyCntlrsFlash
--- a/src/ddr/adm/acq/verifyCntlrsFlash
+++ b/src/ddr/adm/acq/verifyCntlrsFlash
@@ -23,6 +23,15 @@ if [[ x"$npids" != "x" ]] ; then
    exit 0
 fi
 
+# Check if rsh is available
+if ! command -v rsh &> /dev/null; then
+   echo ""
+   echo "Error: rsh is not avaliable on this system."
+   echo "Install rsh package and then restart $SCRIPT"
+   echo ""
+   exit 0
+fi
+
 if hash python3 2> /dev/null; then
     python3 $vnmrsystem/adm/acq/${SCRIPT}3.py $*
 else
